---
label: produit
hide_body: true
fields:
- name: nom
  type: text
  config:
    required: false
  label: nom
  description: Nom du produit
- name: id-produit
  type: text
  config:
    required: true
  label: id-produit
  description: Nom du produit sans majuscules et avec tirets (Starry Night --&gt;
    starry-night)
- name: images
  type: image_gallery
  config: {}
  label: images
  description: Images du produit
- name: prix
  type: number
  label: prix
  description: Prix du produit
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
  description: Description du produit
- name: avec-option
  type: boolean
  label: avec-option
  description: Est ce que le produt à différentes options (tailles/couleurs etc..)
- name: options
  type: field_group_list
  fields:
  - name: option
    type: select
    default: ''
    config:
      required: false
      options:
      - Couleur
      - Taille
      source:
        type: simple
        section: 
        file: 
        path: 
    label: option
    description: Option du produit
  - name: valeur
    type: list
    config:
      use_select: false
      min: 
      max: 
    label: valeur
    description: Valeur de l'option
  config:
    min: 
    max: 
    labelField: 
  label: options
  description: Options du produit
  showOnly:
    field: avec-option
    value: true
pages:
- products/produit-bidon-2.md
- products/produit-test-forestry.md
